### PR TITLE
Updated docs for LazyVim installation

### PR DESCRIPTION
**Pull request by mvykool**
Great job with this theme! I’m somewhat new to the Vim world, and I use LazyVim. I found the installation instructions a bit unclear at first, but I managed to install it easily using the steps I described in the README.md. I tested the steps on two different machines to ensure it works correctly, and it did.

Please let me know your thoughts.

### CODE REVIEW

**Comment by scottmckendry** [comment]
Thanks for the PR. I'm glad to hear you like the theme!

I think it's important to note that this section of the readme is for the lazy.nvim plugin manager. Not the lazyvim distribution. 

While your documentation makes perfect sense in the context of lazyvim, it won't be relevant to those using another distribution or using lazy.nvim in a "from scratch" configuration.

I'd be happy to merge a one-liner that has a link to the lazyvim docs on the topic.

http://www.lazyvim.org/plugins/colorscheme

**Comment by mvykool** [comment]
Oh, I see, I didn't realize that, my bad. Thank you for responding!

**Comment by mvykool** [comment]
I fixed the previous mistake, and added a one-liner with the proper link to their docs, let me know what you think.

**Comment by scottmckendry** [comment]
I have merged the changes 🙂 
Thanks again!

**Pull request merged**
