### PR TITLE
Extras zed

### PR DESCRIPTION
**Pull request by byt3m4st3r**

### CODE REVIEW

**Comment by scottmckendry** [comment]
This is exciting! Finally, I have an excuse to try Zed out. I'd like to have a look at this locally with some different file types to see how close this is to the original Neovim theme.

The only thing I'm having trouble with is installing this theme. Zed's docs don't mention custom themes (that I can see). Maybe adding a readme in the folder that gets created by the action would be a good addition with some more information. 

Also, don't forget to update the table here:
https://github.com/scottmckendry/cyberdream.nvim/blob/b36e66120020c9544771d24c5e304d755276ae2d/lua/cyberdream/extra/init.lua#L8

You may want to enable actions in your fork so you can see the final result 🙂

Let me know when you want me to take a look!

**Comment by byt3m4st3r** [comment]
Hi, thank you for the hint to enable the actions.
Normally, zed would accept one JSON with an array of themes, but generating one JSON for dark and one for light is also OK.
I will fix the variants, add the documentation as you suggested and will reach out to you if I'm done.

**Comment by byt3m4st3r** [comment]
You can take a look if you will :-)

**Comment by scottmckendry** [comment]
Looks great! Thanks for working on this 🙂 
I've made a few small changes, but overall it looks really good. 

The only thing I noticed is that when hovering over warnings, the text isn't very readable:
 
image

Possibly something that can be fixed in a future PR - it could also be that I'm running an early windows build 🤷🏻

**Pull request merged**
